services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.2.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false   # 로컬
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    image: docker.elastic.co/kibana/kibana:9.2.1
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"

  #  logstash:
  #    image: docker.elastic.co/logstash/logstash:9.2.1
  #    container_name: logstash
  #    depends_on:
  #      - elasticsearch
  #    volumes:
  #      - ./logstash/pipeline:/usr/share/logstash/pipeline
  #      - ./logstash/mysql-connector-j.jar:/usr/share/logstash/mysql-connector-j.jar

#  logstash_1:
#    image: docker.elastic.co/logstash/logstash:9.2.1
#    depends_on:
#      - elasticsearch
#    command: >
#      logstash -f /usr/share/logstash/pipeline
#      --pipeline.workers 2
#      --pipeline.batch.size 200
#    volumes:
#      - ./logstash/pipeline-1:/usr/share/logstash/pipeline
#      - ./logstash/mysql-connector-j.jar:/usr/share/logstash/mysql-connector-j.jar
#
#  logstash_2:
#    image: docker.elastic.co/logstash/logstash:9.2.1
#    depends_on:
#      - elasticsearch
#    command: >
#      logstash -f /usr/share/logstash/pipeline
#      --pipeline.workers 2
#      --pipeline.batch.size 200
#    volumes:
#      - ./logstash/pipeline-2:/usr/share/logstash/pipeline
#      - ./logstash/mysql-connector-j.jar:/usr/share/logstash/mysql-connector-j.jar
#
#  logstash_3:
#    image: docker.elastic.co/logstash/logstash:9.2.1
#    depends_on:
#      - elasticsearch
#    command: >
#      logstash -f /usr/share/logstash/pipeline
#      --pipeline.workers 2
#      --pipeline.batch.size 200
#    volumes:
#      - ./logstash/pipeline-3:/usr/share/logstash/pipeline
#      - ./logstash/mysql-connector-j.jar:/usr/share/logstash/mysql-connector-j.jar
#
#  logstash_4:
#    image: docker.elastic.co/logstash/logstash:9.2.1
#    depends_on:
#      - elasticsearch
#    command: >
#      logstash -f /usr/share/logstash/pipeline
#      --pipeline.workers 2
#      --pipeline.batch.size 200
#    volumes:
#      - ./logstash/pipeline-4:/usr/share/logstash/pipeline
#      - ./logstash/mysql-connector-j.jar:/usr/share/logstash/mysql-connector-j.jar

volumes:
  esdata: