spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/blog?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: "0000"

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2s

  jwt:
    secret: b]KL}/?x4_|%L*1XcSCcW7_1HEAKs:2wP-}bW?gD[.o
