spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/blog?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=0000

#path
spring.mvc.servlet.path= /api/v1

# JPA
#spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# always
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=true

spring.jwt.secret=b]KL}/?x4_|%L*1XcSCcW7_1HEAKs:2wP-}bW?gD[.o

#logging
#accesslog ???
server.tomcat.accesslog.enabled=true

server.tomcat.accesslog.prefix=access_log
server.tomcat.accesslog.suffix=.log
server.tomcat.accesslog.pattern=%h %l %u %t "%r" %s %b %D
server.tomcat.accesslog.buffered=false

#basedir ????
server.tomcat.basedir=.
server.tomcat.accesslog.directory=logs

#Actuator
management.endpoints.web.exposure.include=health,info,metrics,threaddump
management.endpoint.health.show-details=always

server.tomcat.mbeanregistry.enabled=true

management.server.port=8081

## Tomcat tuning
#server.tomcat.threads.max=400
#server.tomcat.max-connections=20000
#server.tomcat.accept-count=200
#
## HikariCP tuning
#spring.datasource.hikari.maximum-pool-size=50
#spring.datasource.hikari.minimum-idle=50
#spring.datasource.hikari.connection-timeout=3000

# Redis
spring.data.redis.host= localhost
spring.data.redis.port=6379
spring.data.redis.timeout= 2s