spring:
  application:
    name: blog-service
  profiles:
    active: local
  mvc:
    servlet:
      path: /api/v1
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: never
  jwt:
    secret: ${SPRING_JWT_SECRET:}
  elasticsearch:
    uris: http://localhost:9200
  batch:
    job:
      enabled: false

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

server:
  tomcat:
    accesslog:
      enabled: true
      prefix: access_log
      suffix: .log
      pattern: '%h %l %u %t "%r" %s %b %D'
      buffered: false
      directory: logs
    basedir: .
    mbeanregistry:
      enabled: true

management:
  tracing:
    sampling:
      probability: 1.0
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces
  otlp:
    metrics:
      export:
        enabled: false
  endpoints:
    web:
      exposure:
        include: health,info,metrics,threaddump, prometheus
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        blog.search.outbox.processing.latency: true
  server:
    port: 8081

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
    config-url: /api/v1/v3/api-docs/swagger-config
    url: /api/v1/v3/api-docs
  api-docs:
    path: /v3/api-docs
    enabled: true