input {
  jdbc {
    jdbc_driver_library => "/usr/share/logstash/mysql-connector-j.jar"
    jdbc_driver_class => "com.mysql.cj.jdbc.Driver"
    jdbc_connection_string => "jdbc:mysql://host.docker.internal:3306/blog?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true"
    jdbc_user => "root"
    jdbc_password => "0000"

    jdbc_paging_enabled => true
    jdbc_page_size => 5000
    jdbc_fetch_size => 5000

    statement => "
      SELECT
        p.post_id AS postId,
        p.title AS title,
        COALESCE(p.content, '') AS content,
        p.author_id AS authorId,
        p.view_count AS viewCount,
        p.like_count AS likeCount,
        p.created_at AS createdAt,
        p.post_status AS postStatus
      FROM post p
      WHERE p.post_status = 'PUBLISHED'
        AND p.deleted_at IS NULL
        AND p.post_id <= 2500000
      ORDER BY p.post_id ASC
    "
  }
}

filter {
  mutate {
    convert => {
      "postid" => "integer"
      "authorid" => "integer"
      "viewcount" => "integer"
      "likecount" => "integer"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "post_search_v4"
    document_id => "%{postid}"
    action => "index"
  }
}